name: Update Solar Data

on:
  workflow_dispatch:      # This line creates the Button
  schedule:
    - cron: '*/15 * * * *'

jobs:
  fix-my-solar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: pip install growattServer requests

      - name: Run Script
        env:
          GROWATT_USER: ${{ secrets.GROWATT_USER }}
          GROWATT_PASSWORD: ${{ secrets.GROWATT_PASSWORD }}
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
        run: python fetch_solar.py

      - name: Save Data
        run: |
          git config --global user.name "SolarBot"
          git config --global user.email "bot@noreply.github.com"
          git add solar_data.json
          git commit -m "Update" || exit 0
          git push
