name: Update Solar Data

on:
  workflow_dispatch:      # Allows manual click
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 mins

permissions:
  contents: write

jobs:
  run-solar-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v3

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 3. Install Tools (Directly)
        run: |
          pip install growattServer requests

      - name: 4. Run Python Script
        env:
          GROWATT_USER: ${{ secrets.GROWATT_USER }}
          GROWATT_PASSWORD: $
          {{ secrets.GROWATT_PASSWORD }}
        run: python fetch_solar.py

      - name: 5. Save Results
        run: |
          git config --global user.name "SolarBot"
          git config --global user.email "bot@noreply.github.com"
          git add solar_data.json
          git commit -m "Updated solar stats" || exit 0
          git push
